AWSTemplateFormatVersion: 2010-09-09
Description: This template creates Nested stack with parameterized S3 bucket location

Parameters:
  AllowedSSHIP:
    Description: The IP address allowed to SSH to the public EC2 instances
    Type: String
    Default: 0.0.0.0/0

  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
    Type: AWS::EC2::KeyPair::KeyName
    Default: group13

  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium

  TemplateBucketName:
    Description: Name of the S3 bucket containing nested stack templates
    Type: String
    Default: nt548-labs

  TemplateVersion:
    Description: Version or path prefix for the templates in S3
    Type: String
    Default: ""

Resources:        
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${TemplateBucketName}.s3.amazonaws.com/${TemplateVersion}vpc-cfn.yaml
      TimeoutInMinutes: 10

  NATStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      TemplateURL: !Sub https://${TemplateBucketName}.s3.amazonaws.com/${TemplateVersion}nat-cfn.yaml
      TimeoutInMinutes: 10

  RouteTablesStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VPCStack
      - NATStack
    Properties:
      TemplateURL: !Sub https://${TemplateBucketName}.s3.amazonaws.com/${TemplateVersion}rt-cfn.yaml
      TimeoutInMinutes: 10

  SecurityGroupsStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      TemplateURL: !Sub https://${TemplateBucketName}.s3.amazonaws.com/${TemplateVersion}sg-cfn.yaml
      TimeoutInMinutes: 10
      Parameters:
        AllowedSSHIP: !Ref AllowedSSHIP

  EC2Stack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VPCStack
      - RouteTablesStack
      - SecurityGroupsStack
    Properties:
      TemplateURL: !Sub https://${TemplateBucketName}.s3.amazonaws.com/${TemplateVersion}ec2-cfn.yaml
      TimeoutInMinutes: 10
      Parameters:
        KeyName: !Ref KeyName
        InstanceType: !Ref InstanceType

Outputs:
  PublicInstanceIP:
    Description: Public IP address of the Public Instance
    Value: !GetAtt EC2Stack.Outputs.PublicInstanceIP

  PrivateInstancePrivateIP:
    Description: Private IP address of the Private Instance
    Value: !GetAtt EC2Stack.Outputs.PrivateInstancePrivateIP